stages:
  - test
  - quality

test_job:
  stage: test
  image: python:3.10
  script:
    - pip install -r requirements.txt
    - pytest tests/unit/

code_quality_job :
    stage : quality
    allow_failure: true
    script :
        - flake8 .
