stages:
  - quality
  - test
  - build
  - deploy


code_quality_job :
    stage: quality
    allow_failure: true
    script:
        - python -m flake8

        
test_job:
  stage: test
  image: python:3.10
  script:
    - pip install -r requirements.txt
    - pytest tests/unit/

build_job:
  stage: build
  image: docker:dind
  services:
      - docker:dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker pull $CI_REGISTRY_IMAGE:latest || true
    - docker build --cache-from $CI_REGISTRY_IMAGE:latest --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA --tag $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
    - docker push $CI_REGISTRY_IMAGE:latest

deploy_job:
  stage: deploy
  before_script:
    - chmod 400 $SSH_KEY
  script:
    - ssh -o StrictHostkeyChecking=no -i $SSH_KEY root@159.89.16.25 "
        docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY &&
        docker ps -a -q | xargs docker stop | xargs docker rm &&
        docker run -d -p 8000:8000 $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA "