stages:
  - quality
  - test
  - build
# deploy
  
code_quality_job :
    stage: quality
    allow_failure: true
    script:
        - flake8 .
        
test_job:
  stage: test
  image: python:3.10
  script:
    - pip install -r requirements.txt
    - pytest tests/unit/

build_job:
  stage: build
  image: docker:24.0.4
  services:
    - docker:24.0.4-dind
  script:
    - docker build -t project-13-sml .
    - echo ${HUB_DOCKER_TOKEN} |
      docker login -u ${HUB_DOCKER_USERNAME} --password-stdin
    - docker tag project-13-sml:latest medlao/project-13-sml:latest
    - docker push medlao/project-13-sml:latest
    - docker logout
