stages:
  - quality
  - test
  - build
# deploy

variables:
  CONTAINER_IMAGE: registry.gitlab.com/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:$CI_COMMIT_SHORT_SHA

code_quality_job :
    stage: quality
    allow_failure: true
    script:
        - flake8 .
        
test_job:
  stage: test
  image: python:3.10
  script:
    - pip install -r requirements.txt
    - pytest tests/unit/

build_job:
  stage: build
  image: docker:dind
  services:
      - docker:dind
  before_script:
    - export CI_PROJECT_NAMESPACE=$(echo "$CI_PROJECT_NAMESPACE" | tr '[:upper:]' '[:lower:]')
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build --pull --no-cache --rm=true . --tag=$CONTAINER_IMAGE
    - docker push $CONTAINER_IMAGE