stages:
  - quality
  - test
  - build
  - deploy

code_quality_job :
    stage: quality
    image: python:3.10
    allow_failure: true
    script:
        - pip install flake8
        - flake8 .

test_job:
  stage: test
  image: python:3.10
  script:
    - pip install -r requirements.txt
    - pytest

build_job:
  stage: build
  image: docker:dind
  services:
      - docker:dind
  script:
    - docker login -u $DOCKER_HUB_REGISTRY_USER -p $DOCKER_HUB_REGISTRY_PASSWORD $DOCKER_HUB_REGISTRY
    - docker pull $DOCKER_HUB_REGISTRY_IMAGE:latest || true
    - docker build --cache-from $DOCKER_HUB_REGISTRY_IMAGE:latest --tag $DOCKER_HUB_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA --tag $DOCKER_HUB_REGISTRY_IMAGE:latest .
    - docker push $DOCKER_HUB_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
    - docker push $DOCKER_HUB_REGISTRY_IMAGE:latest
  only:
    - master

deploy_job:
  stage: deploy
  before_script:
    - chmod 400 $SSH_KEY
  script:
    - ssh -o StrictHostkeyChecking=no -i $SSH_KEY root@159.89.16.25 "
        docker login -u $DOCKER_HUB_REGISTRY_USER -p $DOCKER_HUB_REGISTRY_PASSWORD $DOCKER_HUB_REGISTRY &&
        docker ps -a -q | xargs docker stop | xargs docker rm &&
        docker run -d -p 80:8000 $DOCKER_HUB_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA "
  only:
    - master